apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kcd-africa-cluster
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-07503de5aa7aa7c5d }
      us-east-1b: { id: subnet-04f3afc6b03e082ec }
      us-east-1c: { id: subnet-02307e626e9c14d3f }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true
  - name: ng-2-builders
    labels: { role: builders }
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
