apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kcdafricademo
  name: kcdafricademo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcdafricademo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kcdafricademo
    spec:
      containers:
      - image: localhost:5000/kcdspringbootimage
        name: kcdspringbootimage
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kcdafricademo
  name: kcdafricademo
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kcdafricademo
  type: ClusterIP
status:
  loadBalancer: {}
